name: Setup

on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: chmod 755 setup.sh
      - run: docker compose up
